server.port=8080

spring.datasource.url=jdbc:oracle:thin:@//AAKASH_19:1522/orclrr
spring.datasource.username=scott
spring.datasource.password=tiger
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver