server.port=${PORT:8080}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}

email.enabled=true
email.from=${EMAIL_FROM}
sendgrid.api.key=${SENDGRID_API_KEY}
sendgrid.api.url=https://api.sendgrid.com/v3/mail/send

logging.level.root=INFO
logging.level.com.example.demo=INFO
logging.level.com.example.demo.service.OtpService=INFO
logging.level.com.example.demo.service.EmailService=INFO
logging.level.com.example.demo.controller.AuthController=INFO